inherit_gem:
  bixby: bixby_default.yml

AllCops:
  TargetRubyVersion: 2.6.4
  TargetRailsVersion: 6.0.0
  DisplayCopNames: true
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - 'app/javascript/**/*'
    - 'node_modules/**/*'
    - 'vendor/**/*'
    - 'lib/tasks/derivativo/**/*'
    - 'tmp/**/*'

Style/BracesAroundHashParameters:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/RedundantSelf:
  Enabled: false
