inherit_gem:
  rubocul: rubocul_default.yml

inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 3.1.3
  TargetRailsVersion: 7.0.4

CUL/CapybaraScreenshots:
  Description: 'Disallow calls to save_screenshot in feature specs.'
  Enabled: true
  VersionAdded: '3.2.2'
  Include:
    - 'spec/**/*'
