inherit_gem:
  rubocul: rubocul_default.yml

inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 3.0.3
  TargetRailsVersion: 7.0
  Exclude:
    - 'app/javascript/**/*'
    - 'bin/**/*'
    - 'db/**/*'
    - 'lib/tasks/**/*'
    - 'node_modules/**/*'
    - 'vendor/**/*'
    - 'tmp/**/*'

# If we also want to disable this rule in another project, we'll end up disabling it in
# the rubocul gem instead.
Style/RedundantSelf:
  Enabled: false

RSpec/ExampleLength:
  Max: 7
  Exclude:
    - 'spec/derivativo/conversion/office_helpers_spec.rb'
    - 'spec/derivativo/file_helper_spec.rb'

RSpec/NestedGroups:
  Max: 4

RSpec/MultipleMemoizedHelpers:
  Enabled: false

Metrics/MethodLength:
  Max: 15
  Exclude:
    - 'lib/hyacinth/client.rb'

Style/Documentation:
  Enabled: false
