dist: focal
language: ruby
cache:
  bundler: true
  npm: true
  yarn: true
  directories:
    - /tmp/downloads

rvm:
  - 2.6.4

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  matrix:
    - NODE_VERSION=12

jdk: 'openjdk11'

addons:
  chrome: stable

before_install:
  - sudo apt update
  - "echo 'gem: --no-document' > ~/.gemrc"
  - gem update --system
  - gem install bundler
  - travis/install-dependencies.sh

before_script:
  - nvm install $NODE_VERSION
  - nvm use $NODE_VERSION
  - npm install -g yarn
  - npm --version
  - yarn install
  - bundle exec rake derivativo:setup:config_files TIKA_JAR_PATH=/tmp/downloads/tika/tika-app.jar
