manifest:
  "@context": "http://iiif.io/api/presentation/2/context.json"
  "@id": "http://example.org/iiif/book1/manifest"
  "@type": "sc:Manifest"
  "logo":
    "@id": "http://cdn.cul.columbia.edu/ldpd-toolkit/img/crown-bts-24x24.png"
  sequences : []
  structures : []
canvas :
  "@type" : "sc:Canvas"
  images : []
image :
  "@type" : "sc:Annotation"
  motivation : "sc:Painting"
  resource :
    "@type" : "dctypes:Image"
    format : "image/jpeg"
    service:
      "@context": "http://iiif.io/api/image/2/context.json"
      profile : "http://iiif.io/api/image/2/level2.json"
range :
  "@type" : "sc:Range"
  "members" : []
sequence :
  "@type" : "sc:Sequence"
  "viewingDirection" : "left-to-right"
  "viewingHint" : "individuals"
directions :
  - left-to-right
  - right-to-left
  - top-to-bottom
  - bottom-to-top
hints :
  - individuals
  - paged
  - continuous
  - multi-part
  - non-paged
  - top
  - facing-pages
