default: &default
  run_queued_jobs_inline: false
  remote_request_api_key: 'changethis'
  #ffmpeg_binary_path: '/usr/local/bin/ffmpeg'
  #ffprobe_binary_path: '/usr/local/bin/ffprobe'
  #ghostscript_binary_path: 'gs'
  ghostscript_binary_path: 'gs'
  tika_jar_path: '/path/to/your/tika-app.jar'

development:
  <<: *default
  run_queued_jobs_inline: true
  working_directory: <%= Rails.root.join('tmp', 'development', 'working_directory') %>

test:
  <<: *default
  run_queued_jobs_inline: true
  working_directory: <%= Rails.root.join('tmp', 'test', 'working_directory') %>
