name: CI

on:
  push:
    branches: [ '*' ]

jobs:
  ci-rails-app:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['2.7.5']
    env:
      RAILS_ENV: test
      NOKOGIRI_USE_SYSTEM_LIBRARIES: true

    steps:
      - uses: actions/checkout@v2
      - uses: FedericoCarboni/setup-ffmpeg@v1
        id: setup-ffmpeg
      - uses: jmservera/libreoffice-action@v0.3.0-alpha
        name: Libreoffice Convert
      - name: Update apt
        run: sudo apt update
      - name: Install libxslt for nokogiri gem (required for version < 1.11)
        run: sudo apt-get install -y libxml2-dev libxslt-dev
      - name: libvips
        run: sudo apt -y install libvips42
      - name: ghostscript
        run: sudo apt -y install ghostscript
      - name: Add --no-document option to .gemrc file to speed up bundle install
        run: "echo 'gem: --no-document' > ~/.gemrc"
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - name: Config files
        run: bundle exec rake derivativo:config_files
      - name: Run CI task
        run: bundle exec rspec
